Update Openpyxl-format-cloner.py
CellRange updated to MergedCellRange

Solving the following error 
in <module>
    inicioM=searchM.end()
AttributeError: 'NoneType' object has no attribute 'end'